INSERT INTO offers (slug, title, user_id, location, city, country, "category", end_date, description)
VALUES ('EVNT-20170512', 'Video footage for a whole wedding', 'k9', ST_GeomFromText('POINT(18.6432498 54.3572596)',4326), 'Gdańsk', 'Poland', 'EVNT', to_timestamp(1544014105), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20180501', '3D modelling', 'k9', ST_GeomFromText('POINT(9.7877402 53.5586941)',4326), 'Hamburg', 'Germany', 'EVNT', to_timestamp(1515156505), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('AGR-20182102', 'Crash investigation', 'k9', ST_GeomFromText('POINT(9.6364691 53.7538372)',4326), 'Elmshorn', 'Germany', 'AGR', to_timestamp(1519217305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20181010', 'Surveillance', 'k9', ST_GeomFromText('POINT(10.7068629 52.4056194)',4326), 'Wolfsburg', 'Germany', 'EVNT', to_timestamp(1536929305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('SUR-20171001', 'Video inspection', 'k9', ST_GeomFromText('POINT(8.5962045 53.1201552)',4326), 'Bremen', 'Germany', 'SUR', to_timestamp(1523450905), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20171002', 'Bridge Inspection (video)', 'k9', ST_GeomFromText('POINT(8.6445086 50.1761128)',4326), 'Frankfurt am Main', 'Germany', 'EVNT', to_timestamp(1544014105), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('AGR-20172412', 'Trees analysis', 'k9', ST_GeomFromText('POINT(13.7524004 51.0832206)',4326), 'Dresden', 'Germany', 'AGR', to_timestamp(1515156505), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20172409', 'Rail Line Monitoring', 'k9', ST_GeomFromText('POINT(14.6785713 51.1095345 )',4326), 'Löbau', 'Germany', 'EVNT', to_timestamp(1519217305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20180309', 'Footage of Winter Camp Excitement', 'k9', ST_GeomFromText('POINT(12.7065873 53.9734916)',4326), 'Gnoien', 'Germany', 'EVNT', to_timestamp(1536929305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20180610', 'Video footage for a whole wedding', 'k9', ST_GeomFromText('POINT(14.5355257 53.4462312)',4326), 'Szczecin', 'Poland', 'EVNT', to_timestamp(1523450905), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-20180607', 'Crop monitoring', '0G', ST_GeomFromText('POINT(13.9360235 53.9654684)',4326), 'Rankwitz', 'Germany', 'EVNT', to_timestamp(1541249305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('AGR-20180612', 'Pipeline Monitoring', '0G', ST_GeomFromText('POINT(13.3246084 54.5992539)',4326), 'Breege', 'Germany', 'AGR', to_timestamp(1514119705), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('SUR-201806612', 'New Years Eve roof inspection', '0G', ST_GeomFromText('POINT(9.4546738 51.3162416)',4326), 'Kassel', 'Germany', 'SUR', to_timestamp(1513946905), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
 ('EVNT-201822611', 'Wind Farm Blade Inspections', '0G', ST_GeomFromText('POINT(4.8434325 52.3717926)',4326), 'Amsterdam', 'Netherlands', 'EVNT', to_timestamp(1523450905), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
 ('SUR-201822601', 'Powerline Inspection', '0G', ST_GeomFromText('POINT(10.0145478 53.5491974)',4326), 'Hamburg', 'Germany', 'SUR', to_timestamp(1541249305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-201830601', 'Cell Power Inspections', '0G', ST_GeomFromText('POINT(10.1563099 53.6038857)',4326), 'Hamburg', 'Germany', 'EVNT', to_timestamp(1514119705), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-201830607', 'Event footage in the centere', '0G', ST_GeomFromText('POINT(9.9193932 53.5537377)',4326), 'Hamburg', 'Germany', 'EVNT', to_timestamp(1513946905), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('EVNT-201831807', 'Proposal banner', '0G', ST_GeomFromText('POINT(10.0055514 53.5514669)',4326), 'Hamburg', 'Germany', 'EVNT', to_timestamp(1516625305), 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

INSERT INTO offers_results (offer_id, result_code) VALUES
 (1, 'IMG'), (1, 'DHM'), (1, 'TIV'), (1, 'MDL'),
 (2, 'IMG'), (2, 'DHM'), (2, 'TIV'), (2, 'MDL'),
 (3, 'IMG'), (3, 'DHM'), (3, 'TIV'), (3, 'MDL');
INSERT INTO offers_results (offer_id, result_code, value) VALUES
 (4, 'IMG', null), (4, 'DHM', null), (4, 'TIV', null), (4, 'MDL', null), (4, 'OTH', 'Drone flight display'), (4, 'OTH', 'Drone flight lesson'),
 (5, 'IMG', null), (5, 'DHM', null), (5, 'TIV', null), (5, 'MDL', null), (5, 'OTH', 'Drone flight lesson'), (5, 'OTH', 'Drone flight display');

UPDATE offers SET job_area = ST_GeomFromText('POLYGON((18.578559458255768 54.3847561202123, 18.582679331302643 54.38855462060335, 18.57426792383194 54.391053442287, 18.578559458255768 54.3847561202123))', 4326) WHERE id = any(array[2,3,5,8,10,12,14]);
UPDATE offers SET job_area = ST_GeomFromText('POINT(18.578559458255768 54.3847561202123)', 4326) WHERE id = any(array[1,3,5,7,9,11,13,15,16,17,18]);

insert into bids (offer_id, user_id, price, currency)
VALUES (1, '0G', 200.10, 'EUR'), (2, '0G', 110.10, 'EUR'), (5, '0G', 1000.10, 'EUR'), (12, 'k9', 310.10, 'EUR'), (15, 'k9', 20.10, 'EUR'), (17, 'k9', 20.10, 'EUR');

UPDATE offers SET status = 1 WHERE id = any(array[1,12]);
UPDATE offers SET status = 2 WHERE id = any(array[2,15]);
UPDATE offers SET status = 3 WHERE id = any(array[17,5]);