import global_types from '../../../actions';

export const VOIVODESHIPS_DATA_PARSED = 'Map/VOIVODESHIPS_DATA_PARSED';

export const WEATHER_DATA_FETCHED = 'Map/WEATHER_DATA_FETCHED';

export const VOIVODESHIP_CHECKED = 'Map/VOIVODESHIP_CHECKED';

export default {
  VOIVODESHIPS_DATA_PARSED,
  WEATHER_DATA_FETCHED,
  VOIVODESHIP_CHECKED
}
