import global_types from '../../../actions';

export const VOIVODESHIPS_DATA_PARSED = 'Map/VOIVODESHIPS_DATA_PARSED';

export const WEATHER_DATA_FETCHED = 'Map/WEATHER_DATA_FETCHED';

export const VOIVODESHIP_CHECKED = 'Map/VOIVODESHIP_CHECKED';

export const VOIVODES_DATA_FETCHED = 'Map/VOIVODES_DATA_FETCHED';

export const MAP_BOUNDS_CHANGED = "Map/MAP_BOUNDS_CHANGED";

export default {
  VOIVODESHIPS_DATA_PARSED,
  WEATHER_DATA_FETCHED,
  VOIVODESHIP_CHECKED,
  VOIVODES_DATA_FETCHED,
  MAP_BOUNDS_CHANGED
};
